### ISSUE TITLE
Locks duckdb file while in use

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/sqltools-duckdb-driver#1]
Need to have it close the connection after query run:

![image](https://github.com/evidence-dev/sqltools-duckdb-driver/assets/58074498/6e64b769-8de5-462e-bb9c-6aae37f0597b)

**Comment by csjh** [comment]
Looks like opening the database in readonly mode prevents this, which should be fine as long as SQLTools never tries to modify the DB

**Comment by archiewood** [comment]
Fixed in 0.0.2
