### ISSUE TITLE
Unable to view schema for a table.

### ISSUE THREAD

**Issue by aebrahim** [evidence-dev/sqltools-duckdb-driver#11]
I am getting the following error popup when I click on a table:

```
Request connection/GetChildrenForTreeItemRequest failed with message: Catalog Error: Table with name <table_name> does not exist! Did you mean "<schema>.<table_name>"?
```

**Comment by brunowego** [comment]
@archiewood I get the same issue where, to replicate the issue I made this repo https://github.com/brunowego/evidence-bug.

Try follow the developer guide.

**Comment by archiewood** [comment]
Hi @brunowego 

Is this bug with Evidence (https://github.com/evidence-dev/evidence) , or with this DuckDB SQLtools extension?

**Comment by brunowego** [comment]
Thank you for the quick response. The problem is with the "evidence", sorry, I'll create the issue in "evidence" repo. Thanks.
