### ISSUE TITLE
db explorer not working properly column names can't show?

### ISSUE THREAD

**Issue by tyw214** [evidence-dev/sqltools-duckdb-driver#19]
when trying to explore the table to see columns I get this error in vscode:

Request connection/GetChildrenForTreeItemRequest failed with message: Catalog Error: Table with name entities does not exist! Did you mean "iasset_iasset.entities"?

any reason why?

**Comment by archiewood** [comment]
duplicate of https://github.com/evidence-dev/sqltools-duckdb-driver/issues/18
