### ISSUE TITLE
Switch from read-only mode to read-write mode for in memory connections

### ISSUE THREAD

**Issue by wisemuffin** [evidence-dev/sqltools-duckdb-driver#4]
# Problem

When connection to duckdb via an in memory connection and trying to do write operations (creature/update/delete). We get the following error:

`Invalid Error: Cannot execute statement of type "CREATE" on database "<database_name>" which is attached in read-only mode!`

Archie has pointed me to the code that is currently causing all in memory connections to only open sqltools-duckdb in read only: [sqltools-duckdb-driver](https://github.com/evidence-dev/sqltools-duckdb-driver/blob/c2a74fcbcb58dad4f77f2bf9191225188949bc73/src/ls/driver.ts#L33)

# Example use case of in memory 

My use case is actually for an onboarding process I am setting up for some new hires. I have taken the work the dbt folk did for their [jaffle-shop-template](https://github.com/dbt-labs/jaffle-shop-template). I then just removed the dbt part so that potential hires can write some sql transformation (using no transformation tools).

I am sure there are some CI use case which could also benefit.

For reference i am working on this for Australia's NSW Department of Education onboarding for data people (they get given a range of tools such as duckdb and evidence): [nsw_doe_data_case_study](ttps://github.com/wisemuffin/nsw_doe_data_case_study)

# Current limiation

We talked about just enabling a read-write setting for in memory connection.

The only downside is that while the connection is open, READWRITE locks the db.

Ideally a user would be able to have an open connection to duckdb via sqltools and then still access duckdb by evidence and other reporting tools.

**Comment by archiewood** [comment]
doing a bit more research on this today.

As i suspected, any READWRITE connection that we open will lock the DB. Great explanation [here](https://github.com/duckdb/duckdb/issues/1119#issuecomment-785053780) 

so we have a couple of options I can think of:
1. Naively implement READWRITE: this will mean when using SQLTools, you will not be able to use other processes (eg Evidence) to access the DB
2. Add a setting for READWRITE: you choose in the connection config if you want to be able to write in the db. You can toggle this on for when writing and off for when not. 
3. Close the DuckDB connection after every query. This should release the lock. However as described in the above comment, this is likely to be a performance drag.

**Comment by archiewood** [comment]
On a bit more research, 3. Seems to be a bit antipattern for DuckDB. 

I've added support along the lines of 2, in https://github.com/evidence-dev/sqltools-duckdb-driver/commit/8fe980c485eeb1ab88780a7cf1f76dbdf9043f4e.

This is released in 0.0.3

**Comment by wisemuffin** [comment]
@archiewood thank you so much! You have made my onboarding process so much easier. This is working a treat for me.

Also i dont need to close the duckdb connection in sqltools when using evidence. Maybe if i have a long running write job running in SQLtools and then run a query from evidence i am guessing that is when it will through an error.

**Comment by archiewood** [comment]
I've found edge cases where I get a read-write locking error
In particular:
1. Connect to SQL tools, (but don't run any queries yet)
    1. This creates a .wal file.  
2. Then connect to Evidence / something else
3. Throws error
