### ISSUE TITLE
All views within a DB are shown within each schema

### ISSUE THREAD

**Issue by radders1981** [evidence-dev/sqltools-duckdb-driver#6]
When expanding the views branch of the explorer within a schema, all of the views present within the database are shown, rather than just the views that are in that particular schema.

**Comment by archiewood** [comment]
TY for reporting.

Are you seeing  this happen for you for tables also, or just with views?

**Comment by pma99car** [comment]
Not on tables, only on views

**Comment by archiewood** [comment]
closed by https://github.com/evidence-dev/sqltools-duckdb-driver/commit/df8314d008c3ab7e2c53efad79d87c990115f3b6

released in v0.0.4
