### ISSUE TITLE
0.9.0 support

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/sqltools-duckdb-driver#8]

**Comment by archiewood** [comment]
waiting for: https://github.com/duckdb/duckdb/issues/9113

**Comment by solomspd** [comment]
Just wanted to leave this as a head up. This should be addressed with today's release of [duckdb 0.9.1](https://github.com/duckdb/duckdb/releases/tag/v0.9.1). Looking forward to this plugins next release :smile:.

**Comment by solomspd** [comment]
duckdb and duckdb-async seem to have been updated to 0.9.1

**Comment by archiewood** [comment]
Support for DuckDB 0.9.1 is now released in v0.0.5

Please upgrade your VSCode extension - if you have problems, open an issue.
